name: Build and push specification files

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch all history for all branches
        fetch-depth: 0

    - name: Install asciidoc
      run: sudo ./p4-16/spec/install-asciidoctor-linux.sh

    - name: Build p4-16/spec
      run: |
        source /usr/local/rvm/scripts/rvm
        make -C p4-16/spec

    - name: Build p4-16/psa
      run: |
        source /usr/local/rvm/scripts/rvm
        make -C p4-16/psa

    - name: Build api/charter
      run: |
        source /usr/local/rvm/scripts/rvm
        make -C api/charter

    - name: Upload spec artifacts
      uses: actions/upload-artifact@v4
      with:
        name: spec
        path: |
          p4-16/spec/P4-16-spec.html
          p4-16/spec/P4-16-spec.pdf
          p4-16/spec/resources/figs

    - name: Upload PSA spec artifacts
      uses: actions/upload-artifact@v4
      with:
        name: psa-spec
        path: |
          p4-16/psa/PSA.html
          p4-16/psa/PSA.pdf
          p4-16/psa/charter/P4_Arch_Charter.html
          p4-16/psa/figs

    - name: Upload API charter artifacts
      uses: actions/upload-artifact@v4
      with:
        name: api-charter
        path: |
          api/charter/P4_API_WG_charter.pdf
