name: Build and push specification files

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        # Fetch all history for all branches
        fetch-depth: 0

    - name: Install asciidoc
      run: sudo ./p4-16/spec/install-asciidoctor-linux.sh

    - name: Build p4-16/spec
      run: |
        source /usr/local/rvm/scripts/rvm
        make -C p4-16/spec

#   - name: Build p4-16/psa
#     run: |
#       source /usr/local/rvm/scripts/rvm
#       make -C p4-16/psa

#   - name: Build api/charter
#     run: |
#       source /usr/local/rvm/scripts/rvm
#       make -C api/charter

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: spec-builds
        path: |
          p4-16/spec/P4-16-spec.html
          p4-16/spec/P4-16-spec.pdf

#         p4-16/spec/build/P4_API_WG_charter.html
#         p4-16/psa/build/PSA.html
#         p4-16/psa/build/PSA.pdf
#         p4-16/psa/build/P4_Arch_Charter.html
